### ISSUE TITLE
pagination on /all-posts

### ISSUE THREAD

**Issue by zenhack** [zenhack/iron-blogger2#1]
Right now the page literally loads *all* posts, eagerly, from the beginning of time. It should load the first however many, and then provide a page-oriented interface.

**Comment by zenhack** [comment]
@jywarren, I just pushed an implementation of this. I haven't pushed it to openshift yet, and probably won't do so tonight. want to have a look and see if you think the UI is reasonable?

**Comment by jywarren** [comment]
Looks good! someday we could use Bootstrap's numbered pagination, if we want the ability to jump to a page: http://getbootstrap.com/components/#pagination
