### ISSUE TITLE
send reminder notifications

### ISSUE THREAD

**Issue by fiendish** [zenhack/iron-blogger2#10]
Send reminder notifications to bloggers who haven't yet met their N per M post schedule.
Possibly make the notifications configurable by the blogger ("Remind me to post if not done yet # hours before period ends").

**Comment by zenhack** [comment]
So, the current testing site is hosted on openshift, and apparently the outgoing email support is a little flaky (goes through EC2, which gets blacklisted a lot), and they suggest using an external SMTP server.

We definitely need outgoing email, for this and other stuff - but it needs some figuring. If someone wants to investigate, that would be much appreciated.

//cc @paultag

**Comment by fiendish** [comment]
Give it a gmail account

**Comment by zenhack** [comment]
I suppose we could just do that. Fair enough.

**Comment by zenhack** [comment]
The code for this (at least a basic version of it) is in place now, but it isn't actually sending out reminders, because I can't get the account configured. I seem to be locked out of the gmail account I set up, and I'm failing to make another...

Why does email suck so much?

**Comment by zenhack** [comment]
This is mostly done now; I made a mailgun account and plugged the credentials into the boston instance. I'm still futzing with DNS settings to make everybody's mail server happy, and once that's done I'll have to set up a cron job or something. I expect this to be done this weekend though.

**Comment by zenhack** [comment]
This is working, I'm going to close.
