### ISSUE TITLE
initial setup instructions

### ISSUE THREAD

**Issue by jywarren** [zenhack/iron-blogger2#16]
I haven't worked in flask for a while and am not super familiar. I tried `ironblogger serve` and got a 'no wsgi' error.

I figured i had to run `sudo python setup.py install` but that also errors; perhaps it's really been a long time and I don't even have some basic dependencies:

    ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
 #include "pyconfig.h"

Or maybe this is off-track. Now trying `pip install Flask` and `pip install wsgi`

**Comment by jywarren** [comment]
Hmm, that didn't work either. I must confess Flask illiteracy!

**Comment by zenhack** [comment]
For dev purposes I usually use virtualenv. The README is a bit out of 
date, I'll update it tonight.

Quoting Jeffrey Warren (2015-06-03 11:54:31)

>    I haven't worked in flask for a while and am not super familiar. I
>    tried ironblogger serve and got a 'no wsgi' error.
> 
>    I figured i had to run sudo python setup.py install but that also
>    errors; perhaps it's really been a long time and I don't even have some
>    basic dependencies:
> ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
> 
>    #include "pyconfig.h"

You're probably missing python-dev or something?

> 
>    Or maybe this is off-track. Now trying pip install Flask and pip
>    install wsgi

Not the issue, totally my fault. Like I said, will document better 
tonight.

**Comment by jywarren** [comment]
thanks!

**Comment by zenhack** [comment]
I just pushed some changes to the README. Have a look and see if it makes things more clear?

**Comment by jywarren** [comment]
I think i'll have a chance to check it out today, or worst case Saturday.
Thanks!

**Comment by jywarren** [comment]
Hmm, I got

`/home/warren/sites/iron-blogger2/.venv/build/lxml/src/lxml/includes/etree_defs.h:14:31:
fatal error: libxml/xmlversion.h: No such file or directory`

https://gist.github.com/jywarren/dfb1dfe2be2cf9740593

Sorry, I'm a bit out of it re: flash environments... I have python-libxml2
and libxml2 installed. Any ideas? Thanks for the help!

**Comment by zenhack** [comment]
Do you have libxml2-dev installed? What distro are you on?

Quoting Jeffrey Warren (2015-06-04 15:17:36)

**Comment by jywarren** [comment]
I do, and I'm on Ubuntu 14.04.

**Comment by zenhack** [comment]
Quoting Jeffrey Warren (2015-06-04 17:43:27)

>    I do, and I'm on Ubuntu 14.04.

Try adding `--system-site-packages` when you create the virtualenv? I 
think otherwise it won't see the stuff installed system wide.

**Comment by jywarren** [comment]
Super. works now. Thanks!
