### ISSUE TITLE
Using bower with openshift is a nightmare

### ISSUE THREAD

**Issue by zenhack** [zenhack/iron-blogger2#20]
Thanks to @jywarren, the website is substantially nicer looking now. His patch pulled in some dependencies on things like bootstrap, jquery, and it uses bower to manage them.

Unfortunately, the version of npm available on openshift is too old to install bower. I also just have a philosophical problem with having node.js as a dependency for a flask app.

Right now, as a workaround, I've got a branch locally that I'm just committing the assets to, and then pushing them to openshift. This is horrid.

One possible solution: bower requires everything to be in a git repo anyway; why don't we just use git submodules instead? deploying would be way easier.

@jywarren, what do you think?

**Comment by jywarren** [comment]
I've had people grimace at me for suggesting submoduling static assets, but
I really have no idea why. I have no problem with it -- bower is nice in
that it doesn't pull in the whole repo, just the dist folder (or whatever's
specified for production) and manages version dependencies, but we're not
doing any heavy lifting in this setup, so its not a big deal. We really
don't even need jquery at this point so we could remove that too.

**Comment by zenhack** [comment]
Will bootstrap break if we take out jquery? it specifies it as a dependency, and if we're doing submodules it won't pull things in recursively.

I'm going to go ahead and re-do that as submodules. I think it will make maintaining things a lot easier.

**Comment by jywarren** [comment]
I don't think bootstrap will break... i think it's possible we don't even
need to use bootstrap js -- for now, I'm only using the styles.

**Comment by zenhack** [comment]
Okay. I'm going to send a pr in a sec that just converts the current thing over to submodules (jquery included), which I'd like you to sanity check. We can try removing jquery as a separate patch.

**Comment by jywarren** [comment]
ok - i'm about to head out and will be traveling the weekend but will try
to give it a go. tnx!
