### ISSUE TITLE
Difficult to see who is "late"

### ISSUE THREAD

**Issue by hlieberman** [zenhack/iron-blogger2#25]
Currently, there is no easy way to tell which bloggers are slacking for the current period of blogging.  You can estimate by looking at the status page and comparing to the ledger, but that's cludgy at best.

Perhaps the status page should represent who is missing as well?

**Comment by zenhack** [comment]
Maybe just put a "yet to post" list at the end of each week's summary on the status page? @jywarren, what do you think?

**Comment by zenhack** [comment]
@hlieberman, @jywarren, I pushed a solution to this. It's live on  the test instance, but I'm unhappy with it visually. Probably should be less vertical. @jywarren, any ideas?

**Comment by jywarren** [comment]
You could perhaps list them comma-delimited? You don't like that it takes
up so much space? Should you be able to quickly scan the list
alphabetically or otherwise?

**Comment by zenhack** [comment]
hm. I'll have to see how the comma separation looks. As far as quickly finding things --- I imagine the list will be a bit smaller when people are actively participating. Right now it's a lot easier to get a handle on who *did* post, just because it's a shorter list.

@hlieberman what are your thoughts?

**Comment by zenhack** [comment]
I ended up going with the comma separated list. It's live on the test instance.

**Comment by jywarren** [comment]
I think it looks good! Would it be helpful to have each username link to
their blog? Eventually we might imagine having a profile page for each user
showing their IB history.
