### ISSUE TITLE
tests not passing (probably an env setup error on my part)

### ISSUE THREAD

**Issue by jywarren** [zenhack/iron-blogger2#28]
I see:

````
______________ ERROR collecting tests/test_assign_rounds.py _______________
import file mismatch:
imported module 'tests.test_assign_rounds' has this __file__ attribute:
  /home/warren/sites/iron-blogger2/build/lib.linux-i686-2.7/tests/test_assign_rounds.py
which is not the same as the test file we want to collect:
  /home/warren/sites/iron-blogger2/tests/test_assign_rounds.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
````

and the same for each of the other 6 tests. I'm not familiar enough with python testing to know how this is supposed to work and I did come across this recommending unique test names: http://youku.io/questions/271425/py-test-test-discovery-failure-when-tests-in-different-directories-are-called

So this is probably more of a call for help than a bug -- can you point me at a resource to educate myself a bit on how this is supposed to work? Thanks!

**Comment by zenhack** [comment]
This looks like you may have forgotten the `-e` in `pip install -e .` when setting up the virtualenv?

**Comment by zenhack** [comment]
@jywarren, you mentioned in person you thought you'd gotten this working... can I close?

**Comment by jywarren** [comment]
I actually haven't... I started fresh and got the same error. Still Ubuntu
14.04... any ideas or next steps to debug?

**Comment by zenhack** [comment]
Silly question: have you done what it suggests, and delete all of the `.pyc` and `__pycache__` files?

What's the exact set of commands you're running to set everything up?

**Comment by jywarren** [comment]
I did -- and it didn't help, i got the same error. I re-installed from scratch with your new instructions, to the line. I can try again? The site runs fine, its just tests that don't pass. Shall I upload a gist of the entire process?

**Comment by zenhack** [comment]
Quoting Jeffrey Warren (2015-06-15 19:51:16)

>  Shall I upload a gist of the entire process?

Probably more efficient than me playing 20 questions --- please do.

**Comment by jywarren** [comment]
Figured it out. I had been missing Ubuntu packages libxml2-dev libxslt1-dev:

`sudo apt-get install libxml2-dev libxslt1-dev` solved it. Thanks for your patience! Would it be helpful to put these requirements into the readme? I'm happy to if it doesn't seem inappropriate.

**Comment by zenhack** [comment]
It would probably make sense hito do so --- Archlinux doesn't split headers into separate packages, so I didn't hit this. I would very much appreciate the patch.
