### ISSUE TITLE
Nicer looking html/css

### ISSUE THREAD

**Issue by zenhack** [zenhack/iron-blogger2#3]
I've mostly been working on basic functionality, but the site is ugly as sin.

**Comment by zenhack** [comment]
@alexose, still up for this?

**Comment by jywarren** [comment]
I'd like to help. Not that familiar with this framework, but I'd like to use Bower to manage static assets like css/js libraries. Where do web-accessible files live?

**Comment by jywarren** [comment]
Ah, it's flask. I guess I can make a /ironblogger/static/ directory but as i recall there's something to config about routing static assets, no?

**Comment by jywarren** [comment]
Untested pull request in https://github.com/zenhack/iron-blogger2/pull/17

**Comment by jywarren** [comment]
Ready to go on #17, but I was also wondering if we could just make the front page (/) the all-posts view?

**Comment by zenhack** [comment]
Sure, defaulting to all-posts sounds like a good idea. The one detail that needs paying attention to is that right now the front page is the only place with the nav, so that would have to be added (probably on every page somewhere).

**Comment by zenhack** [comment]
And it's live: http://ironblogger-idenhardt.rhcloud.com/

Are the fonts looking right for you? They seem to be defaulting to some fallback for me; a look at firefox's console reveals 404s for a couple of the font files, but I get the same on my local dev server, and it still looks right there.

```
127.0.0.1 - - [04/Jun/2015 21:16:58] "GET /bower_components/sorts-mill-goudy/webfonts/GoudyStM-webfont.woff HTTP/1.1" 404 -
127.0.0.1 - - [04/Jun/2015 21:16:58] "GET /bower_components/sorts-mill-goudy/webfonts/GoudyStM-webfont.ttf HTTP/1.1" 404 -
```

**Comment by zenhack** [comment]
Also, I hate openshift: it's running an ancient version of npm, which can't figure out how to install bower, so I actually just committed all of the bower assets locally and pushed them. grr.

**Comment by jywarren** [comment]
I'm seeing 404s for:

ronblogger-idenhardt.rhcloud.com/static/bower_components/bootstrap/dist/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404 (NOT
FOUND)
http://ironblogger-idenhardt.rhcloud.com/static/bower_components/jquery/dist/jquery.min.js
Failed to load resource: the server responded with a status of 404 (NOT
FOUND)
http://ironblogger-idenhardt.rhcloud.com/static/bower_components/bootstrap/dist/js/bootstrap.min.js
Failed to load resource: the server responded with a status of 404 (NOT
FOUND)
http://ironblogger-idenhardt.rhcloud.com/static/bower_components/bootstrap/dist/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404 (NOT
FOUND)

Hmm, are you sure the bower libs copied up?

**Comment by zenhack** [comment]
Quoting Jeffrey Warren (2015-06-05 15:22:40)

>    I'm seeing 404s for:
>    ronblogger-idenhardt.rhcloud.com/static/bower_components/bootstrap/dist
>    /css/bootstrap.min.css
>    Failed to load resource: the server responded with a status of 404 (NOT
>    FOUND)
>    http://ironblogger-idenhardt.rhcloud.com/static/bower_components/jquery
>    /dist/jquery.min.js
>    Failed to load resource: the server responded with a status of 404 (NOT
>    FOUND)
>    http://ironblogger-idenhardt.rhcloud.com/static/bower_components/bootst
>    rap/dist/js/bootstrap.min.js
>    Failed to load resource: the server responded with a status of 404 (NOT
>    FOUND)
>    http://ironblogger-idenhardt.rhcloud.com/static/bower_components/bootst
>    rap/dist/css/bootstrap.min.css
>    Failed to load resource: the server responded with a status of 404 (NOT
>    FOUND)
>    Hmm, are you sure the bower libs copied up?
>    On Thu, Jun 4, 2015 at 6:18 PM, Ian Denhardt <notifications@github.com>
>    wrote:

>    > Also, I hate openshift: it's running an ancient version of npm, 
>    > which
>    > can't figure out how to install bower, so I actually just committed
>    all of
>    > the bower assets locally and pushed them. grr.

The rule for `dist` in `.gitignore` was blocking these from getting 
added to the repo; It appears to be fixed now. I'm still getting the 
404's about those too fonts, but that's both locally and on the test 
instance.

I really need a better way to get the bower assets in there than just 
committing them to the repo...

**Comment by zenhack** [comment]
I feel like we could use some more padding in those tables.

**Comment by jywarren** [comment]
Tables that are in posts? Screencap?

**Comment by zenhack** [comment]
Quoting Jeffrey Warren (2015-06-06 14:34:57)

>    Tables that are in posts? Screencap?

In things like the status page/ledger. Give me a sec on the screencap.

**Comment by zenhack** [comment]
https://i.imgur.com/Vu6w4Ms.png

**Comment by jywarren** [comment]
If you add the class "table" then the bootstrap default styles should be
applied; sorry, I'm at an airport at the moment!

**Comment by zenhack** [comment]
Okay, thanks for the tip, no worries.

**Comment by zenhack** [comment]
I'm going to go ahead and close this; there's always more work to be done of course, but the site looks pretty reasonable by now. Further UX issues should be opened as specific tasks.

Great work, @jywarren!

**Comment by jywarren** [comment]
Thanks for everything!
