### ISSUE TITLE
shorter per page count in pagination

### ISSUE THREAD

**Issue by jywarren** [zenhack/iron-blogger2#45]
It's a pretty long scroll on a phone... Not sure what it's at currently but maybe 10-20 posts would be good?

**Comment by zenhack** [comment]
Quoting Jeffrey Warren (2015-08-07 14:20:17)

>    It's a pretty long scroll on a phone... Not sure what it's at currently
>    but maybe 10-20 posts would be good?

Right now it's 50. My original reasoning was that with ~30 people this
would let you see at a minimum the current round and change, most of the
time.

I can think of a handful of ways to approach this:

1. Do as you suggest and reduce it
2. Make it configurable (and reduce it on the instance we're using)
3. Make it a function of the number of bloggers
4. Make it a function of time.

Doing (4) would mean that pages might be different sizes, though from
week to week they should be similarly sized.

My gut is that (1) or (2) is probably the right answer. What do other
people think?

// cc @hlieberman, @shaunagm

**Comment by shaunagm** [comment]
This is a question near and dear to my heart!  If you look at the original repo (or rather, Paultag's fork of the original repo) you can see my very first free software code contribution:

https://github.com/paultag/iron-blogger/commit/abe5a57a68ccfd4426f1a73bf6d365c7f19e9173

As the diff makes clear, I favor a greater # of posts, but a configurable version would be fine by me.

**Comment by jywarren** [comment]
:-)

This is mainly an issue on mobile. I've never really thought about
paginating by anything by count, so that's a new one for me... no worries,
this isn't a big deal, it's just many seconds of scrolling to see anything
near the bottom of the page, so I thought I'd ask. Doesn't really seem that
important, and we could in theory display only titles on mobile devices,
with a click to display the whole post or something.

**Comment by zenhack** [comment]
I think at a minimum having a server side config option would be a good thing, but that doesn't immediately translate to something visitors of the site can tweak. It would at least let an administrator tune the count if the default doesn't meet their group's needs (assuming anyone besides us ever uses it, though it would also be nice to be able to tweak for a large or smaller group).

I worry about cluttering up the interface by adding too many knobs to the page. @shaunagm, can you explain why you prefer larger pages?

It would be pretty easy to make the size adjustable by the user; you can already do it actually, though a button would probably be nice:

http://ironblogger-idenhardt.rhcloud.com/posts?page_size=10

(@jywarren, feel free to bookmark that while we continue to discuss)

**Comment by shaunagm** [comment]
The old site didn't have any pagination, so once a post scrolled off the original 15 items, it was lost forever.  Upping the # of items was quicker than configuring the planet to have pagination, and now I'm rather used to it.  With pagination, it's pretty much a non-issue.  If you can set 10 to the default, I'm happy to make ?page_size=50 my bookmark instead.

**Comment by jywarren** [comment]
I am bookmarked, so no urgency here.

**Comment by zenhack** [comment]
Okay. I think I'll add the server side option and shorten the default. One I've done so I'll close this.
