### ISSUE TITLE
punt folks after debt > N

### ISSUE THREAD

**Issue by paultag** [zenhack/iron-blogger2#7]
re-add punting etc

**Comment by zenhack** [comment]
I've implemented much of the scheme described in #8, and it isn't obvious that this plays a role anymore. I'm tempted to close, but first would like to chefk whether others think we need something like this. @fiendish, @paultag?

**Comment by fiendish** [comment]
I'm in favor of eliminating punting given new rules as established in #8.

**Comment by zenhack** [comment]
Alright, I'm going to close this.
